version: '3'
services:
  caddy:
    image: abiosoft/caddy:1.0.3-no-stats
    environment:
      - CADDYPATH=/caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy:/caddy
      - ./logs:/logs
      - ./www:/www
